# Identity Server configuration
# Email configuration for "192.168.0.143"
is:
  email:
    sender-name: 'Support@Hermit'
    sender-address: 'hermitsyahmifouzi@outlook.com'
    network:
      name: 'The Things Stack'
      console-url: 'https://192.168.0.114/console'
      identity-server-url: 'https://192.168.0.114/oauth'

    # If sending email with Sendgrid
    # provider: sendgrid
    # sendgrid:
    #   api-key: '...'              # enter Sendgrid API key

    # If sending email with SMTP
    # provider: smtp
    # smtp:
    #   address:  '...'             # enter SMTP server address
    #   username: '...'             # enter SMTP server username
    #   password: '...'             # enter SMTP server password

  # Web UI configuration for "192.168.0.143":
  oauth:
    ui:
      canonical-url: 'https://192.168.0.114/oauth'
      is:
        base-url: 'https://192.168.0.114/api/v3'

# HTTP server configuration
http:
  cookie:
    block-key: '9dbbbcbe55ee2a0099c721aa42c1cb98ca3943dd218aa48bab0c4969a49a6bb2'                # generate 32 bytes (openssl rand -hex 32)
    hash-key: '690f8ad4b3f599d8c604bb4f21d5aed8ec1f25d4bdb4fb3d772ecbb9fe7b092564bcdadf16682443fa8c9c3236839b00f3dfd975f0b3b6d811218dac629aed0c'                 # generate 64 bytes (openssl rand -hex 64)
  metrics:
    password: 'admin123'               # choose a password
  pprof:
    password: 'admin123'                 # choose a password

# If using custom certificates:
tls:
  source: file
  root-ca: /run/secrets/ca.pem
  certificate: /run/secrets/cert.pem
  key: /run/secrets/key.pem

# Let's encrypt for "192.168.0.143"
# tls:
#   source: 'acme'
#   acme:
#     dir: '/var/lib/acme'
#     email: 'you@192.168.0.143'
#     hosts: ['192.168.0.143']
#     default-host: '192.168.0.143'

# If Gateway Server enabled, defaults for "192.168.0.143":
gs:
  mqtt:
    public-address: '192.168.0.114:1882'
    public-tls-address: '192.168.0.114:8882'
  mqtt-v2:
    public-address: '192.168.0.114:1881'
    public-tls-address: '192.168.0.114:8881'

# If Gateway Configuration Server enabled, defaults for "192.168.0.143":
gcs:
  basic-station:
    default:
      lns-uri: 'wss://192.168.0.114:8887'
  the-things-gateway:
    default:
      mqtt-server: 'mqtts://192.168.0.114:8881'

# Web UI configuration for "192.168.0.143":
console:
  ui:
    canonical-url: 'https://192.168.0.114/console'
    is:
      base-url: 'https://192.168.0.114/api/v3'
    gs:
      base-url: 'https://192.168.0.114/api/v3'
    ns:
      base-url: 'https://192.168.0.114/api/v3'
    as:
      base-url: 'https://192.168.0.114/api/v3'
    js:
      base-url: 'https://192.168.0.114/api/v3'
    qrg:
      base-url: 'https://192.168.0.114/api/v3'
    edtc:
      base-url: 'https://192.168.0.114/api/v3'

  oauth:
    authorize-url: 'https://192.168.0.114/oauth/authorize'
    token-url: 'https://192.168.0.114/oauth/token'
    logout-url: 'https://192.168.0.114/oauth/logout'
    client-id: 'console'
    client-secret: 'console'          # choose or generate a secret

# If Application Server enabled, defaults for "192.168.0.143":
as:
  mqtt:
    public-address: 'https://192.168.0.114:1883'
    public-tls-address: 'https://192.168.0.114:8883'
  webhooks:
    downlink:
      public-address: '192.168.0.114:1885/api/v3'

# If Device Claiming Server enabled, defaults for "192.168.0.143":
dcs:
  oauth:
    authorize-url: 'https://192.168.0.114/oauth/authorize'
    token-url: 'https://192.168.0.114/oauth/token'
    logout-url: 'https://192.168.0.114/oauth/logout'
    client-id: 'device-claiming'
    client-secret: 'device-claiming'          # choose or generate a secret
  ui:
    canonical-url: 'https://192.168.0.114/claim'
    as:
      base-url: 'https://192.168.0.114/api/v3'
    dcs:
      base-url: 'https://192.168.0.114/api/v3'
    is:
      base-url: 'https://192.168.0.114/api/v3'
    ns:
      base-url: 'https://192.168.0.114/api/v3'
